### PR TITLE
docs(community-projects.md): add cnab-rs entry

### PR DESCRIPTION
**Pull request by vdice**
* Adds entry/link to the [cnab-rs](https://github.com/cnabio/cnab-rs) library

### CODE REVIEW

**Comment by carolynvs** [comment]
Is the rust library CNAB 1.0 compliant? @radu-matei

**Comment by vdice** [comment]
Note that a few other pre-existing entries are most likely not CNAB 1.0-compliant.

**Comment by carolynvs** [comment]
Hah, I guess I meant, does it still work with CNAB 1.0? Or has it been broken by 1.0?

**Comment by carolynvs** [comment]
I created a follow-on issue to indicate CNAB spec version support https://github.com/cnabio/cnab.io/issues/30

**Pull request merged**
